#!/bin/bash
set -e

# ProxiCloud One-Line Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/MasonD-007/proxicloud/main/deploy/install.sh | bash

echo "==================================="
echo "ProxiCloud Installer"
echo "==================================="
echo ""

# Check if running on Proxmox
if [ ! -f /etc/pve/.version ]; then
    echo "Error: This script must be run on a Proxmox VE node"
    exit 1
fi

# Install git if missing
if ! command -v git >/dev/null 2>&1; then
    echo "Git not found. Installing Git..."
    apt-get update
    apt-get install -y git
    echo "Git installed successfully: $(git --version)"
else
    echo "Git is already installed: $(git --version)"
fi

# Install Go if missing
if ! command -v go >/dev/null 2>&1; then
    echo "Go not found. Installing Go..."
    GO_VERSION="1.22.6"
    cd /usr/local
    wget -q https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
    rm -rf /usr/local/go
    tar -xzf go${GO_VERSION}.linux-amd64.tar.gz
    rm go${GO_VERSION}.linux-amd64.tar.gz
    echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
    export PATH=$PATH:/usr/local/go/bin
    echo "Go installed successfully: $(go version)"
else
    echo "Go is already installed: $(go version)"
fi

# Install Node.js if missing
if ! command -v node >/dev/null 2>&1; then
    echo "Node.js not found. Installing Node.js 20..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
    echo "Node.js installed successfully: $(node -v)"
else
    echo "Node.js is already installed: $(node -v)"
fi

echo "Prerequisites check complete."

# Create installation directory
INSTALL_DIR="/opt/proxicloud"
echo "Creating installation directory: $INSTALL_DIR"
mkdir -p $INSTALL_DIR
cd $INSTALL_DIR

# Clone repository (or download release in production)
echo "Downloading ProxiCloud..."
if [ -d ".git" ]; then
    echo "Repository already exists, pulling latest changes..."
    git pull
else
    git clone https://github.com/MasonD-007/proxicloud.git .
fi

# Build backend
echo "Building backend..."
cd backend
go build -o proxicloud-api cmd/api/main.go
chmod +x proxicloud-api

# Build frontend
echo "Building frontend..."
cd ../frontend
npm install
npm run build

# Create config and data directories
echo "Setting up configuration..."
mkdir -p /etc/proxicloud
mkdir -p /var/lib/proxicloud
mkdir -p /var/log/proxicloud
if [ ! -f /etc/proxicloud/config.yaml ]; then
    echo ""
    echo "==================================="
    echo "Configuration Setup"
    echo "==================================="
    echo ""
    echo "Please provide your Proxmox configuration details:"
    echo ""
    
    # Prompt for Proxmox IP Address
    read -p "Proxmox IP Address (e.g., 192.168.1.100): " PROXMOX_IP
    
    # Prompt for Proxmox Port (default: 8006)
    read -p "Proxmox Port [8006]: " PROXMOX_PORT
    PROXMOX_PORT=${PROXMOX_PORT:-8006}
    
    # Construct the full URL
    PROXMOX_URL="https://${PROXMOX_IP}:${PROXMOX_PORT}"
    
    # Prompt for Proxmox Node Name
    read -p "Proxmox Node Name [$(hostname)]: " NODE_NAME
    NODE_NAME=${NODE_NAME:-$(hostname)}
    
    # Prompt for API Token ID
    read -p "API Token ID (e.g., root@pam!proxicloud): " TOKEN_ID
    
    # Prompt for API Token Secret (hidden input)
    echo -n "API Token Secret: "
    read -s TOKEN_SECRET
    echo ""
    
    # Prompt for verify SSL (default: true for self-signed certs)
    read -p "Skip SSL verification? (true/false) [true]: " INSECURE
    INSECURE=${INSECURE:-true}
    
    # Prompt for API server settings
    read -p "API Server Host [0.0.0.0]: " API_HOST
    API_HOST=${API_HOST:-0.0.0.0}
    
    read -p "API Server Port [8080]: " API_PORT
    API_PORT=${API_PORT:-8080}
    
    # Prompt for Frontend settings
    read -p "Frontend Host [0.0.0.0]: " FRONTEND_HOST
    FRONTEND_HOST=${FRONTEND_HOST:-0.0.0.0}
    
    read -p "Frontend Port [3000]: " FRONTEND_PORT
    FRONTEND_PORT=${FRONTEND_PORT:-3000}
    
    # Create configuration file with user input
    cat > /etc/proxicloud/config.yaml << EOF
# ProxiCloud Configuration File
# Generated by installer on $(date)

# API Server Configuration
server:
  host: "$API_HOST"
  port: $API_PORT

# Proxmox Configuration
proxmox:
  host: "$PROXMOX_URL"
  node: "$NODE_NAME"
  token_id: "$TOKEN_ID"
  token_secret: "$TOKEN_SECRET"
  insecure: $INSECURE
EOF
    
    echo ""
    echo "Configuration file created at: /etc/proxicloud/config.yaml"
    echo ""
fi

# Install systemd services
echo "Installing systemd services..."

# Create API service
cat > /etc/systemd/system/proxicloud-api.service << 'SERVICE'
[Unit]
Description=ProxiCloud API Server
Documentation=https://github.com/MasonD-007/proxicloud
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root

# Path to the ProxiCloud API binary
ExecStart=/opt/proxicloud/backend/proxicloud-api

# Working directory
WorkingDirectory=/opt/proxicloud/backend

# Configuration file location
Environment="CONFIG_PATH=/etc/proxicloud/config.yaml"

# Restart policy
Restart=on-failure
RestartSec=5s

# Security settings
NoNewPrivileges=true
PrivateTmp=true

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=proxicloud-api

[Install]
WantedBy=multi-user.target
SERVICE

# Get node IP for API URL
NODE_IP=$(hostname -I | awk '{print $1}')

# Create frontend service (with correct API dependency)
cat > /etc/systemd/system/proxicloud-frontend.service << SERVICE
[Unit]
Description=ProxiCloud Frontend Server
Documentation=https://github.com/MasonD-007/proxicloud
After=network-online.target proxicloud-api.service
Wants=network-online.target
Requires=proxicloud-api.service

[Service]
Type=simple
User=root
Group=root

# Path to Node.js and the Next.js server
ExecStart=/usr/bin/npm start

# Working directory (where package.json is located)
WorkingDirectory=/opt/proxicloud/frontend

# Environment variables
Environment="NODE_ENV=production"
Environment="PORT=3000"
Environment="NEXT_PUBLIC_API_URL=http://${NODE_IP}:8080/api"

# Restart policy
Restart=on-failure
RestartSec=5s

# Security settings
NoNewPrivileges=true
PrivateTmp=true

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=proxicloud-frontend

[Install]
WantedBy=multi-user.target
SERVICE

# Reload systemd
systemctl daemon-reload

# Enable and start services
echo "Enabling services..."
systemctl enable proxicloud-api
systemctl enable proxicloud-frontend

echo "Starting services..."
systemctl start proxicloud-api
systemctl start proxicloud-frontend

echo ""
echo "==================================="
echo "Installation Complete!"
echo "==================================="
echo ""
echo "ProxiCloud is now running!"
echo ""
echo "Backend API: http://$NODE_IP:8080"
echo "Frontend UI: http://$NODE_IP:3000"
echo ""
echo "Next steps:"
echo "1. Edit /etc/proxicloud/config.yaml with your Proxmox credentials"
echo "2. Restart services: systemctl restart proxicloud-api"
echo "3. Access the UI at http://$NODE_IP:3000"
echo ""
echo "Service management:"
echo "  - Check status: systemctl status proxicloud-api proxicloud-frontend"
echo "  - View logs: journalctl -u proxicloud-api -f"
echo "  - Stop: systemctl stop proxicloud-api proxicloud-frontend"
echo ""
