#!/bin/bash
# ProxiCloud Proxmox Token Setup Helper
# Guides users through creating and configuring Proxmox API tokens

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${GREEN}═══════════════════════════════════════${NC}"
echo -e "${GREEN}ProxiCloud - Proxmox Token Setup${NC}"
echo -e "${GREEN}═══════════════════════════════════════${NC}"
echo ""

# Function to print colored output
print_info() {
    echo -e "${BLUE}[i]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

print_step() {
    echo -e "${YELLOW}Step $1:${NC} $2"
}

# Introduction
echo "This script will guide you through creating a Proxmox API token"
echo "for ProxiCloud. You'll need access to your Proxmox web interface."
echo ""

# Step 1: Gather information
print_step "1" "Gather Proxmox Information"
echo ""

read -p "Enter your Proxmox host IP or hostname: " PROXMOX_HOST
read -p "Enter your Proxmox node name (e.g., pve): " NODE_NAME

echo ""
print_info "Great! Now let's create an API token in Proxmox..."
echo ""

# Step 2: Instructions for creating token
print_step "2" "Create API Token in Proxmox Web UI"
echo ""
echo "Please follow these steps in your Proxmox web interface:"
echo ""
echo "1. Log in to Proxmox at: https://${PROXMOX_HOST}:8006"
echo ""
echo "2. Navigate to: Datacenter → Permissions → API Tokens"
echo ""
echo "3. Click 'Add' to create a new token with these settings:"
echo "   - User: root@pam (or your preferred user)"
echo "   - Token ID: proxicloud (or any name you like)"
echo "   - Privilege Separation: UNCHECKED (important!)"
echo "   - Comment: ProxiCloud API Access"
echo ""
echo "4. Click 'Add' and COPY the generated token"
echo "   ${YELLOW}⚠️  The token is only shown ONCE!${NC}"
echo ""
echo "5. The token format is: USER@REALM!TOKENID=SECRET"
echo "   Example: root@pam!proxicloud=12345678-1234-1234-1234-123456789abc"
echo ""

read -p "Press ENTER when you have copied your token..."

echo ""

# Step 3: Collect token information
print_step "3" "Enter Token Information"
echo ""

read -p "Enter the User (e.g., root@pam): " TOKEN_USER
read -p "Enter the Token ID (e.g., proxicloud): " TOKEN_ID
read -s -p "Enter the Token Secret: " TOKEN_SECRET
echo ""

echo ""

# Validate inputs
if [ -z "$PROXMOX_HOST" ] || [ -z "$NODE_NAME" ] || [ -z "$TOKEN_USER" ] || [ -z "$TOKEN_ID" ] || [ -z "$TOKEN_SECRET" ]; then
    print_error "All fields are required!"
    exit 1
fi

# Step 4: Test connection
print_step "4" "Test Connection (Optional)"
echo ""

read -p "Would you like to test the connection? (y/n): " TEST_CONN

if [[ "$TEST_CONN" =~ ^[Yy]$ ]]; then
    print_info "Testing connection to Proxmox..."
    
    # Test API call
    response=$(curl -k -s -w "\n%{http_code}" \
        -H "Authorization: PVEAPIToken=${TOKEN_USER}!${TOKEN_ID}=${TOKEN_SECRET}" \
        "https://${PROXMOX_HOST}:8006/api2/json/version" 2>&1 || echo "000")
    
    http_code=$(echo "$response" | tail -n1)
    
    if [ "$http_code" = "200" ]; then
        print_success "Connection successful!"
        version=$(echo "$response" | head -n-1 | grep -o '"version":"[^"]*"' | cut -d'"' -f4)
        print_info "Proxmox version: $version"
    else
        print_warning "Connection test failed (HTTP $http_code)"
        print_warning "This might be due to network issues or incorrect credentials"
        print_info "You can still continue and test later"
    fi
    echo ""
fi

# Step 5: Generate configuration
print_step "5" "Generate Configuration"
echo ""

CONFIG_FILE="config.yaml"

# Ask where to save
read -p "Save configuration to [./config.yaml]: " CUSTOM_PATH
if [ ! -z "$CUSTOM_PATH" ]; then
    CONFIG_FILE="$CUSTOM_PATH"
fi

# Generate configuration file
cat > "$CONFIG_FILE" << EOF
# ProxiCloud Configuration
# Generated by setup-token.sh on $(date)

proxmox:
  host: "${PROXMOX_HOST}"
  port: 8006
  node: "${NODE_NAME}"
  token_user: "${TOKEN_USER}"
  token_id: "${TOKEN_ID}"
  token_secret: "${TOKEN_SECRET}"
  tls_verify: false  # Set to true if you have valid SSL certificates
  timeout: 30

server:
  host: "0.0.0.0"
  port: 8080
  cors_origins:
    - "http://localhost:3000"
    - "https://your-domain.com"

cache:
  enabled: true
  path: "/var/lib/proxicloud/cache.db"
  update_interval: 300  # 5 minutes

analytics:
  enabled: true
  path: "/var/lib/proxicloud/analytics.db"
  retention_days: 30
  collection_interval: 30  # 30 seconds

defaults:
  template:
    storage: "local"
    ostype: "ubuntu"
  container:
    cpu: 2
    memory: 1024
    disk: 9
    network: "name=eth0,bridge=vmbr0,ip=dhcp"
    storage: "local-lvm"
    start_on_boot: true
    unprivileged: true
EOF

print_success "Configuration saved to: $CONFIG_FILE"
echo ""

# Step 6: Security reminder
print_step "6" "Security Reminders"
echo ""
print_warning "IMPORTANT SECURITY NOTES:"
echo ""
echo "1. Keep your token secret secure - it grants full API access"
echo "2. Set proper file permissions on config.yaml:"
echo "   ${YELLOW}chmod 600 $CONFIG_FILE${NC}"
echo ""
echo "3. Do NOT commit config.yaml to version control"
echo "   (It should be in .gitignore already)"
echo ""
echo "4. Consider enabling TLS verification in production:"
echo "   Set 'tls_verify: true' after installing proper SSL certs"
echo ""

# Step 7: Next steps
print_step "7" "Next Steps"
echo ""
echo "Your ProxiCloud configuration is ready!"
echo ""
echo "To start using ProxiCloud:"
echo ""
echo "1. Set proper permissions:"
echo "   ${YELLOW}chmod 600 $CONFIG_FILE${NC}"
echo ""
echo "2. Create required directories:"
echo "   ${YELLOW}sudo mkdir -p /var/lib/proxicloud${NC}"
echo "   ${YELLOW}sudo chown \$USER:\$USER /var/lib/proxicloud${NC}"
echo ""
echo "3. Start the backend:"
echo "   ${YELLOW}CONFIG_PATH=$CONFIG_FILE ./proxicloud-api${NC}"
echo ""
echo "4. Start the frontend:"
echo "   ${YELLOW}cd frontend && NEXT_PUBLIC_API_URL=http://localhost:8080/api npm start${NC}"
echo ""
echo "5. Access ProxiCloud:"
echo "   ${YELLOW}http://localhost:3000${NC}"
echo ""

print_success "Setup complete!"
echo ""
